@startuml "Lexer"

!theme blueprint

namespace lexer {

  enum TokenType {
    
  }

  struct Token {

  }

  namespace tokens {

  }

  class Tokenizer {

  }

  class Parser {
    
  }

  class Compiler {

  }

  class Interpreter {

  }

  
}

@enduml